#!/bin/sh
# chkconfig: 345 10 20
# description: Disable transparent hugepage
# processname: disable-hugepage

. /etc/init.d/functions

start() {
  if test -f /sys/kernel/mm/transparent_hugepage/khugepaged/defrag; then
    echo 0 > /sys/kernel/mm/transparent_hugepage/khugepaged/defrag
  fi
  if test -f /sys/kernel/mm/transparent_hugepage/defrag; then
    echo never > /sys/kernel/mm/transparent_hugepage/defrag
  fi
  if test -f /sys/kernel/mm/transparent_hugepage/enabled; then
    echo never > /sys/kernel/mm/transparent_hugepage/enabled
  fi
}

stop() {
  echo "Nothing to do!"
}

status() {
  if test -f /sys/kernel/mm/transparent_hugepage/khugepaged/defrag; then
    echo -n "/sys/kernel/mm/transparent_hugepage/khugepaged/defrag = "
    cat /sys/kernel/mm/transparent_hugepage/khugepaged/defrag
  fi
  if test -f /sys/kernel/mm/transparent_hugepage/defrag; then
    echo -n "/sys/kernel/mm/transparent_hugepage/defrag = "
    cat /sys/kernel/mm/transparent_hugepage/defrag
  fi
  if test -f /sys/kernel/mm/transparent_hugepage/enabled; then
    echo -n "/sys/kernel/mm/transparent_hugepage/enabled = "
    cat /sys/kernel/mm/transparent_hugepage/enabled
  fi
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    status
    ;;
  *)
    echo "Usage: disable-hugepage {start|stop|status}"
    exit 1
    ;;
esac
exit $?
